/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BTokenRouteImport } from './routes/b.$token'
import { Route as ApiSmartInkRouteImport } from './routes/api.smart-ink'

const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BTokenRoute = BTokenRouteImport.update({
  id: '/b/$token',
  path: '/b/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmartInkRoute = ApiSmartInkRouteImport.update({
  id: '/api/smart-ink',
  path: '/api/smart-ink',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/rooms': typeof RoomsRoute
  '/api/smart-ink': typeof ApiSmartInkRoute
  '/b/$token': typeof BTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/rooms': typeof RoomsRoute
  '/api/smart-ink': typeof ApiSmartInkRoute
  '/b/$token': typeof BTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/rooms': typeof RoomsRoute
  '/api/smart-ink': typeof ApiSmartInkRoute
  '/b/$token': typeof BTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/auth' | '/rooms' | '/api/smart-ink' | '/b/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/auth' | '/rooms' | '/api/smart-ink' | '/b/$token'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/rooms'
    | '/api/smart-ink'
    | '/b/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  RoomsRoute: typeof RoomsRoute
  ApiSmartInkRoute: typeof ApiSmartInkRoute
  BTokenRoute: typeof BTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$token': {
      id: '/b/$token'
      path: '/b/$token'
      fullPath: '/b/$token'
      preLoaderRoute: typeof BTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/smart-ink': {
      id: '/api/smart-ink'
      path: '/api/smart-ink'
      fullPath: '/api/smart-ink'
      preLoaderRoute: typeof ApiSmartInkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  RoomsRoute: RoomsRoute,
  ApiSmartInkRoute: ApiSmartInkRoute,
  BTokenRoute: BTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
